server.port = 9080

spring.application.name=user-service

## Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=0000

## Jpa Config
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

## RabbitMQ Config
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

broker.exchange.user=user.exchange

broker.routing.user-created=user.created

# ACTUATOR
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# PROMETHEUS
management.prometheus.metrics.export.enabled=true

# DEFAULT TAG
management.metrics.tags.application=user-service