server.port = 8081

## Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=0000

## Jpa Config
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

## RabbitMQ Config
spring.rabbitmq.addresses=amqps://piibespy:yGRn96M2zD7Tm2HRn8w_frw5veiuBFXi@jackal.rmq.cloudamqp.com/piibespy

broker.exchange.user=user.exchange

broker.routing.user-created=user.created